Lab3
iWenrad/vitalii-bodiak-IPZ-31 pull request #3
Opened 2023-10-06 09:02 UTC by iWenrad

2023-10-06 11:41 UTC, vozniuk-lntu requested changes
1. контейнер бокові падінги 15пх
2. розтягни хедер падінгами посилань
3. фон на герої зроби комбінований bg
4. накинь це на прихований заголовок https://gist.github.com/luxplanjay/6f6936b1bba7afe006fa9317b07b6045
5. кнопки фільтрів без відступів
6. в портфоліо одна секція
7. прописати всюди санс-серіф для перестраховки
8. в карточці теж підпис обгорни в дів і подивись що з посиланням на зображенні

2023-10-06 11:41 UTC, vozniuk-lntu commented on index.html
> +                        <h2 class="what-we-do__title title">Чим ми займаємося</h2>
відступ до списка маржин

2023-10-06 11:41 UTC, vozniuk-lntu commented on index.html
> +                        <h2 class="our-command__title title">Наша команда</h2>
відступ до списка маржин

2023-10-06 11:41 UTC, vozniuk-lntu commented on index.html
> +                                <h3 class="our-command__name">Ігор Дем'яненко</h3>
візьми заголовок і підпис в дів і накинь верхні і нижні падінги

2023-10-11 11:10 UTC, iWenrad commented
Перевірте, будь ласка

2023-10-13 10:37 UTC, vozniuk-lntu approved these changes

2023-10-13 10:37 UTC, vozniuk-lntu commented on portfolio.html
> +                        <button type="button" class="assortment__button _focus">Усі</button>
зроби списком кнопки

2023-10-13 10:37 UTC, vozniuk-lntu commented on portfolio.html
>                  <section class="main__assortment assortment">
один прихований заголовок на секцію

2023-10-13 10:37 UTC, merged